from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(318, 394)
        Form.setMinimumSize(QtCore.QSize(318, 394))
        Form.setMaximumSize(QtCore.QSize(318, 394))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.password_input = QtWidgets.QLineEdit(parent=self.frame_2)
        self.password_input.setGeometry(QtCore.QRect(40, 160, 200, 30))
        self.password_input.setMinimumSize(QtCore.QSize(200, 30))
        self.password_input.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        self.password_input.setFont(font)
        self.password_input.setText("")
        self.password_input.setObjectName("password_input")
        self.username_input = QtWidgets.QLineEdit(parent=self.frame_2)
        self.username_input.setGeometry(QtCore.QRect(40, 70, 200, 30))
        self.username_input.setMinimumSize(QtCore.QSize(200, 30))
        self.username_input.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        self.username_input.setFont(font)
        self.username_input.setText("")
        self.username_input.setObjectName("username_input")
        self.username_label = QtWidgets.QLabel(parent=self.frame_2)
        self.username_label.setGeometry(QtCore.QRect(50, 100, 161, 20))
        self.username_label.setStyleSheet("\n"
"background-color: rgb(255, 0, 0);")
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(parent=self.frame_2)
        self.password_label.setGeometry(QtCore.QRect(50, 190, 171, 21))
        self.password_label.setStyleSheet("\n"
"background-color: rgb(255, 0, 0);")
        self.password_label.setObjectName("password_label")
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(80, 30, 100, 50))
        self.pushButton.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login"))
        self.password_input.setPlaceholderText(_translate("Form", "Password:"))
        self.username_input.setPlaceholderText(_translate("Form", "Username:"))
        self.username_label.setText(_translate("Form", "123123"))
        self.password_label.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "Log in"))
